### ISSUE TITLE
[DOCS] Node Version 

### ISSUE THREAD

**Issue by Zemerik** [EddieHubCommunity/HealthCheck#15]
### Description

To run the Health Check website, we need ‘v21+‘ of node, or else users will not be able to add their repo on the app. To fix this issue, we can add the version of node required somewhere in the README to avoid confusion.

### Screenshots

![image](https://github.com/user-attachments/assets/55a83675-27c7-4aca-9e4f-f622267c1868)

**Comment by eddiejaoude** [comment]
Thank you for raising 👍
