### ISSUE TITLE
Check items do not expand

### ISSUE THREAD

**Issue by CalvinWilkinson** [EddieHubCommunity/HealthCheck#155]
### Description

Each check item in the image below does not give the ability to be expanded for what I assume is more information.
When hovering the mouse over the expand icons all the way to the right of each item, the icon is not clickable and the mouse cursor does not change to signal that it is clickable.

### Screenshots

![image](https://github.com/user-attachments/assets/a6ba0b6a-f34d-4fe4-85f0-1c4f9e32b8e7)

**Comment by eddiejaoude** [comment]
Oh good spot 👍  I removed the clickable link but forgot to remove the icon 🤦‍♂️

**Comment by Bashamega** [comment]
I can work on this

**Comment by eddiejaoude** [comment]
> I can work on this

Sure, I have assigned it to you @Bashamega - I think the best solution here, is to only show the icon when there is a url and the item is clickable (any questions let me know)
