### ISSUE TITLE
[FEATURE] Repo rater badge

### ISSUE THREAD

**Issue by Bashamega** [EddieHubCommunity/HealthCheck#158]
### Description

Add the RepoRater badge to the README

```
[![RepoRater](https://repo-rater.eddiehub.org/api/badge?owner=EddieHubCommunity&name=HealthCheck)](https://repo-rater.eddiehub.org/rate?owner=EddieHubCommunity&name=HealthCheck)
```

[![RepoRater](https://repo-rater.eddiehub.org/api/badge?owner=EddieHubCommunity&name=HealthCheck)](https://repo-rater.eddiehub.org/rate?owner=EddieHubCommunity&name=HealthCheck)

**Comment by eddiejaoude** [comment]
Great idea 👍  I will update the issue description with more information on how to do it

**Comment by ahmaddonishyar** [comment]
I like to contribute please assign me.

**Comment by sago78** [comment]
I'm also available to contirbute.

**Comment by eddiejaoude** [comment]
Thank you. It looks like this has already been done, so I will close the issue
