### ISSUE TITLE
Missing UI margin

### ISSUE THREAD

**Issue by Bashamega** [EddieHubCommunity/HealthCheck#159]
### Description

I think there should be a margin below the add button.

Add margin top to footer, so every page it has a gap

### Screenshots

![image](https://github.com/user-attachments/assets/dab1b541-38d2-42c3-a31b-016b3f0af395)

**Comment by eddiejaoude** [comment]
Good spot, I think the footer, should have a margin applied to the top so on every page there is a gap

**Comment by Bridgetamana** [comment]
Can you please assign this to me, I can work on this.

**Comment by eddiejaoude** [comment]
Sure @Bridgetamana , it is assigned to you
