### ISSUE TITLE
Navbar not updating the active state on click

### ISSUE THREAD

**Issue by Muhammad-Owais-Warsi** [EddieHubCommunity/HealthCheck#17]
### Description

In the navbar when navigating to different routes , the active state of the element is not changed . Currently in code `aria-current` is used . If using that only, we want to update the state, we have to force render the component. Instead we can use  `useState` and update the active state correctly.  The problem is shown in the screenshot below.

### Screenshots

![Screenshot 2024-07-12 225009](https://github.com/user-attachments/assets/a78e1e28-4df5-4c13-93ea-2b68538fc340)

**Comment by eddiejaoude** [comment]
Thank you for raising the issue, yes this needs to be fixed 👍

**Comment by Muhammad-Owais-Warsi** [comment]
> Thank you for raising the issue, yes this needs to be fixed 👍

Welcome @eddiejaoude , should I raise the PR ?

**Comment by eddiejaoude** [comment]
Sure, I can assign it to you 👍  

Please pull the latest changes, as I just pushed a few minutes ago

**Comment by Muhammad-Owais-Warsi** [comment]
Sure 👍

**Comment by eddiejaoude** [comment]
Sorry I just noticed I renamed one of the Flagsmith feature flags but I didn't update the Flagsmith config - so you might get an error. I will fix that right now

**Comment by eddiejaoude** [comment]
Fixed. You can now import the feature flags into your Flagsmith account using the file `flagsmith.json`

**Comment by Muhammad-Owais-Warsi** [comment]
@eddiejaoude  so sorry, i mistakenly , pushed my API Key..

**Comment by Muhammad-Owais-Warsi** [comment]
> @eddiejaoude so sorry, i mistakenly , pushed my API Key..

Finally , corrected it 👍
