### ISSUE TITLE
[FEATURE] Add a copy button.

### ISSUE THREAD

**Issue by Bashamega** [EddieHubCommunity/HealthCheck#173]
### Description

Hello:)
I think it is a good idea to add a copy badge icon.

### Screenshots

![image](https://github.com/user-attachments/assets/e8660e35-ff29-4d3d-b71a-2a9473dea3e0)

### Additional information

I would like to work on this

**Comment by eddiejaoude** [comment]
Great idea 👍  I have assigned it to you
