### ISSUE TITLE
[FEATURE] GitHub Action for Scorecard

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/HealthCheck#189]
### Description

- add GH Action
- add badge to README

https://github.com/ossf/scorecard?tab=readme-ov-file

**Comment by eddiejaoude** [comment]
Thank you, I have assigned it to you

**Comment by eddiejaoude** [comment]
The badge in the README does not seem to work.

The report and data look great https://scorecard.dev/viewer/?uri=github.com/EddieHubCommunity/HealthCheck

<img width="1026" alt="Screenshot 2024-08-30 at 10 59 03" src="https://github.com/user-attachments/assets/9d25c334-f867-437e-b7d2-cc7e3d614e6a">

**Comment by Bashamega** [comment]
I have fixed it in #196

**Comment by eddiejaoude** [comment]
Thank you
