### ISSUE TITLE
[FEATURE] badge should link to the latest report on the healthcheck site

### ISSUE THREAD

**Issue by loftwah** [EddieHubCommunity/HealthCheck#193]
### Description

Currently, the health check badge displayed in the GitHub README links directly to the badge image itself. To enhance the functionality and provide more valuable information to users, the badge should be updated to link to the latest health check report on the HealthCheck site.

**Feature Request:**

Update the health check badge in the GitHub README so that clicking on it redirects users to the latest health check report available on the HealthCheck site instead of just displaying the badge image.

**Expected Outcome:**

* The health check badge in the README should serve as a dynamic link.
* When clicked, the badge should navigate users directly to the most recent health check report on the HealthCheck site.
* This will provide quick access to the detailed status and metrics of the project.

### Screenshots

![image](https://github.com/user-attachments/assets/744c7f72-9571-451b-b1cc-744e60f7dd60)

![image](https://github.com/user-attachments/assets/8a9a30cb-7872-4915-afb7-1ee336893e0b)

**Comment by Bashamega** [comment]
Hello:)

I think this issue, can be resolved by the user by embed the health check report

**Comment by eddiejaoude** [comment]
Great idea! 👍 

Wrapping it in a link to a report would make it link to a specific report. I think it would be better to wrap it in a special link (and in the example badge in the app), that links to the latest report for that repo

**Comment by eddiejaoude** [comment]
Deploying now 🎉  I will test out on our README first (I can't 100% test until deployed, but should work 🤞 )

**Comment by eddiejaoude** [comment]
It works 🎉 

[![HealthCheck](https://healthcheck.eddiehubcommunity.org/api/badges/report/clzr3h1ti0000daor5pydhz8y)](https://healthcheck.eddiehubcommunity.org/api/report/latest/clzr3h1ti0000daor5pydhz8y)

**Comment by loftwah** [comment]
I added it to [Linkarooie](https://github.com/loftwah/linkarooie) and it works.

**Comment by eddiejaoude** [comment]
Great! Thanks for checking! The preview has a bug, just deploying a fix now

**Comment by eddiejaoude** [comment]
Preview Fixed

<img width="611" alt="Screenshot 2024-09-09 at 14 56 52" src="https://github.com/user-attachments/assets/8108687e-a010-474d-8e15-b5ef9bdd7d30">
