### ISSUE TITLE
[BUG] App crashes when running checks

### ISSUE THREAD

**Issue by renenielsendk** [EddieHubCommunity/HealthCheck#199]
### Description

The app crashes when clicking the button "Run checks"

### Screenshots

https://github.com/user-attachments/assets/9b43ac78-1cd3-40d4-981f-b21ccee89a22

**Comment by eddiejaoude** [comment]
Good spot 👍  I have just pushed a fix 💪

**Comment by eddiejaoude** [comment]
Seems to be fixed now 🎉
