### ISSUE TITLE
[FEATURE] Don't make the user to leave the page (Github Repository button)

### ISSUE THREAD

**Issue by renenielsendk** [EddieHubCommunity/HealthCheck#200]
### Description

Make button `</> Github repository` open in `target="_blank"`

It's an inconvenience for the user if they click the button, and they are navigated away from the UI.

### Screenshots

https://github.com/user-attachments/assets/da65b270-b06c-4fb7-9791-c45d3e3f1b2f

**Comment by eddiejaoude** [comment]
Great suggestion 👍  Thank you

**Comment by bruno-keiko** [comment]
I'd like to address this issue!

**Comment by eddiejaoude** [comment]
Sure @bruno-keiko I will assign it to you
