### ISSUE TITLE
[BUG] My repositories are added multiple times.

### ISSUE THREAD

**Issue by renenielsendk** [EddieHubCommunity/HealthCheck#203]
### Description

I personally don't think it should be possible adding the same repository twice. Do some kind of validation on the URL.

This would also prevent the system from being flooded with duplicates.
This is normally not an issue if the scope of the things added is the same user, but when having lists of "All repositories" and similar, this will start to become an issue, if the same repository occurs multiple times.

Could possibly be linked with #204

**Comment by eddiejaoude** [comment]
I don't see this happening too often, I think people will only add repos they are interested in. 

We could use this metric of how many times a repo has been added - it could make a fun page.

I agree it would be more efficient to have a single source of truth per repo.

But as this is not an issue for now, I am going to close, but something we could consider in the future - thank you for the feedback
