### ISSUE TITLE
[FEATURE] Validate repository ownership/maintainability

### ISSUE THREAD

**Issue by renenielsendk** [EddieHubCommunity/HealthCheck#204]
### Description

I don't know if it's possible, but adding validation whether the one adding the repository can actually maintain it would be nice.

This would prevent outside parties from adding my repository.
This is not an issue right now, but if you also want to prevent duplicate repositories, this would be one way of doing it.

Goes well with #203

**Comment by eddiejaoude** [comment]
Yep this is something that can be done, but some people wanted to make suggestions to the repo that they might only contribute to, so we left it open to be able to add any public repo.

If the maintainer adds the repo, they get a bit more information, for example the traffic stats of the repo.

I will close this suggestion for now, as I am keen to keep things more "open" for now to get more feedback. 

Thank you for raising though.
