### ISSUE TITLE
Branches check should be added to ignored settings

### ISSUE THREAD

**Issue by dehenne** [EddieHubCommunity/HealthCheck#205]
### Description

> we use main as the default branch in all our repos. isn't that how it is now on github?
there was a lot of discussion about master and main ^^

- make branches check optional
- default branch `main` might have a bug as shows a [warning](https://github.com/EddieHubCommunity/HealthCheck/issues/205#issuecomment-2322990518)

### Screenshots

![image](https://github.com/user-attachments/assets/e69cb33d-0c84-49b9-b7d1-0d8e48c876cf)

### Additional information

the following repo is involved: https://github.com/QUIQQER/QUIQQER

**Comment by eddiejaoude** [comment]
Yep `main` is the default and recommended branch 👍  The error is suggesting you have too many open branches (the total amount of branches)

**Comment by dehenne** [comment]
Hm, what is the max amount? Basically, this is difficult, especially when several people are working on it.

We use a branching strategy with next branches. Ok, V1 is still old, so I can delete a few. But for example if I support and develop 3 versions then I have:

main
next-1.x
1.*
next-2.x
2.*
next-3.x
3.*

What happens if I have more major? 👀

**Comment by eddiejaoude** [comment]
The numbers we have are not perfect, they are a starting point - so they probably need tweaking.

This is what we currently have, what would your suggestion be for these values?

https://github.com/EddieHubCommunity/HealthCheck/blob/9a64815dc514fef8630ae6d8f9201075e07daed1/src/utils/checks/branches.js#L2-L3

**Comment by dehenne** [comment]
I wouldn't have taken a number at all 😆 ... I had probably asked if certain branches existed. 

For example, main, v.*, next-*.* I would ignore. If strange branch names exist, then I would complain about that. 

But I don't want to complain here. 😅

In any case, the number is difficult. When I think of projects where we work in a large team and several features are developed at the same time, you often have several dozen feat-* branches, which then dissolve after a few weeks.

But they are there for a short time 🤔

**Comment by renenielsendk** [comment]
@dehenne
Couldn't some of your branches be moved to tags? It seems like you're maintaining some branches that are over a year old.

From what I can tell, it looks like you're using semantic versioning along with branches to manage your versions. However, I don't quite see why tags wouldn't suffice instead.

If you're following true semantic versioning, you wouldn't be able to update a branch like 1.3.1 without releasing a new version.

Unless I'm misunderstanding something, using branches in this way might defeat the purpose of semantic versioning.

**Comment by eddiejaoude** [comment]
We do have the ability to hide certain checks for that repo under settings, I can add the `branches` check to the settings page, and then you can ignore that check

*note: currently experimenting with which ones are allowed to be ignored/hidden from the repo for the user*

<img width="1307" alt="Screenshot 2024-08-31 at 17 42 34" src="https://github.com/user-attachments/assets/ee09e3a2-bec9-467e-b0e4-8d2a47681367">

**Comment by dehenne** [comment]
@renenielsendk 

v1 = old branching strategy
v2 = new branching (semver with tags)

I have to cleanup V1. Anyway, next branches and 1.*, 2.* will still exists.

@eddiejaoude 

Would be a nice workaround ☺️

**Comment by eddiejaoude** [comment]
Great 👍  I will add it tomorrow

**Comment by dehenne** [comment]
oh, btw, now i know why i said "main is not considered" :dagger: 

![image](https://github.com/user-attachments/assets/abe0e8bd-718e-4376-8edd-feb711ef663f)

**Comment by eddiejaoude** [comment]
oh that looks like a bug 🤔  - I will check it out, thank you for the screenshot

**Comment by eddiejaoude** [comment]
You can now remove `default branch` and `branches` check in settings

<img width="1273" alt="Screenshot 2024-09-09 at 11 39 13" src="https://github.com/user-attachments/assets/164833f5-430b-4349-af00-490c6514d7bf">

**Comment by eddiejaoude** [comment]
I can't replicate the default branch `main` issue, so I will close for now until we get more feedback from people

<img width="484" alt="Screenshot 2024-09-09 at 11 40 26" src="https://github.com/user-attachments/assets/60c3cd70-b9b1-4bbf-9ff9-8825d3b8fb69">
