### ISSUE TITLE
Why IN THE WORLD this github application REQUESTS WRITE ACCESS to my repositories?

### ISSUE THREAD

**Issue by bedbad** [EddieHubCommunity/HealthCheck#213]
### Description

I tried to check out this app on my repository and requested WRITE ACCESS. 
I denied and I really, really thing that's borderline criminal because most users of HealthCheck don't notice that which may corrupt and delete their HealtChecked public repositories.

### Screenshots

![Screenshot from 2024-09-08 18-46-37](https://github.com/user-attachments/assets/2fd74dde-8ee4-4eb9-adb9-b51831b41898)

**Comment by eddiejaoude** [comment]
It should **ONLY** require read access to **PUBLIC** repos

https://github.com/EddieHubCommunity/HealthCheck/blob/f577c87624777e142349c58a97338b7d5322229c/src/app/api/auth/%5B...nextauth%5D/route.js#L16

I will double check the permissions now. Thank you for raising 👍 

Please note, I will reply later regarding, you breaking out our communities code of conduct and what action will be taken.

**Comment by eddiejaoude** [comment]
This has now been fixed in PR https://github.com/EddieHubCommunity/HealthCheck/pull/214

Deploying now. Once deployed to production I will `revoke` all user tokens in the GitHub OAuth app, which will force all users to log in again with the reduced `readonly` permissions.

**Comment by eddiejaoude** [comment]
Now it is deployed and all user tokens have been revoked, this actually does not work because more permissions is required to read the repo's statistics

https://docs.github.com/en/rest/metrics/traffic?apiVersion=2022-11-28#get-top-referral-sources

<img width="1673" alt="Screenshot 2024-09-08 at 21 04 13" src="https://github.com/user-attachments/assets/5127c6a3-aa07-4407-81d2-a80101d0d842">

From the official GitHub docs:

> The fine-grained token must have the following permission set:
> 
> - "Administration" repository permissions (read)

**Comment by eddiejaoude** [comment]
For more clarification, if the write permissions are removed, GitHub's API returns the following error

```js
data: {
      message: 'Must have push access to repository',
      documentation_url: 'https://docs.github.com/rest/metrics/traffic#get-page-views',
      status: '403'
    }
```
