### ISSUE TITLE
Playwright tests fail as need default feature flags

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/HealthCheck#22]
### Description

When running the automated tests on GitHub Actions, we do not want to load tests Flagsmith's servers, so we will run with default flags

> You can run in offline mode, local evaluation mode or just use defaults

Discussion from the Flagsmith Discord server.

> [!NOTE]
> Playwright GitHub Action will fail until this is fixed

What I am trying to use
https://github.com/EddieHubCommunity/HealthCheck/blob/23d35eef3210cf07c6200e5a1c1b833cb1b485f3/src/config/flagsmith.js#L14-L17

Here are the official docs
https://docs.flagsmith.com/clients/javascript#providing-default-flags

**Comment by eddiejaoude** [comment]
<img width="1269" alt="Screenshot 2024-07-12 at 19 45 37" src="https://github.com/user-attachments/assets/825525e2-11ec-48a5-9c89-a45353142c29">

**Comment by eddiejaoude** [comment]
Tried `defaultFlags` on `init` but still failing on CI, logged an issue with the flagsmith js sdk https://github.com/Flagsmith/flagsmith-js-client/issues/237

**Comment by dan-mba** [comment]
> Tried `defaultFlags` on `init` but still failing on CI, logged an issue with the flagsmith js sdk [Flagsmith/flagsmith-js-client#237](https://github.com/Flagsmith/flagsmith-js-client/issues/237)

According to the [docs](https://docs.flagsmith.com/clients/server-side#managing-default-flags) there isn't a `defaultFlags` setting, but is a `defaultFlagHandler` function that returns the default value.

**Comment by eddiejaoude** [comment]
Sorry @dan-mba it was late for me last night, after more investigation, I included the server side docs up there, but I need it client side, here are the docs https://docs.flagsmith.com/clients/javascript#providing-default-flags

I still can't get it working though, so any thoughts appreciated, here is where I am using it 
https://github.com/EddieHubCommunity/HealthCheck/blob/23d35eef3210cf07c6200e5a1c1b833cb1b485f3/src/config/flagsmith.js#L14-L17

**Comment by dan-mba** [comment]
> Sorry @dan-mba it was late for me last night, after more investigation, I included the server side docs up there, but I need it client side, here are the docs https://docs.flagsmith.com/clients/javascript#providing-default-flags
> 
> 
> 
> I still can't get it working though, so any thoughts appreciated, here is where I am using it 
> 
> https://github.com/EddieHubCommunity/HealthCheck/blob/23d35eef3210cf07c6200e5a1c1b833cb1b485f3/src/config/flagsmith.js#L14-L17
> 
> 
> 
> *note: I have updated the issue description*

I don't think `flag.name` should be in an array.
The array returned from each map should include a string for the object property name as the first item of the array then its contents second.

**Comment by eddiejaoude** [comment]
Thanks for checking again Dan after my confusing issue description. I am wrapping the `map` in `Object.fromEntries` so the   default flags I am passing are this (output from console.log)

```js
{
  tagline: {
    enabled: true,
    value: 'LOCAL: How friendly is your Open Source Repo?'
  },
  checks: { enabled: true, value: '["topics","description","url"]' },
  news: {
    enabled: true,
    value: 'LOCAL: Have you seen our latest feature XYZ?'
  }
}
```

**Comment by dan-mba** [comment]
I found the problem
`flagsmith.init()` throws for being unable to connect.
I added a try/catch that ignores the error & it makes the defaults work

**Comment by eddiejaoude** [comment]
oh wow amazing 🔥 ! thank you ❤️ I am going to try it now

**Comment by eddiejaoude** [comment]
OMG it works perfectly, thank you @dan-mba !!
