### ISSUE TITLE
Can't sign in production (official deployed app)

### ISSUE THREAD

**Issue by jcubic** [EddieHubCommunity/HealthCheck#243]
### Description

Got an error when tried to log in:

If this project is not public, maybe it's worth explaining who can login.

### Screenshots

![Przechwycenie obrazu ekranu_2024-09-11_20-27-27](https://github.com/user-attachments/assets/b2673e70-4faa-4491-b691-9d594f55530f)

### Additional information

Got Error in URL:

https://healthcheck.eddiehubcommunity.org/api/auth/error?error=%0AInvalid%20%60prisma.account.update()%60%20invocation%3A%0A%0A%0AAn%20operation%20failed%20because%20it%20depends%20on%20one%20or%20more%20records%20that%20were%20required%20but%20not%20found.%20Record%20to%20update%20not%20found.

Decoded:

> Invalid `prisma.account.update()` invocation:
> 
>
> An operation failed because it depends on one or more records that were required but not found. Record to update not found.

**Comment by eddiejaoude** [comment]
Yes it is public, let me look at the logs. Thank you for reporting

**Comment by eddiejaoude** [comment]
I was able to log in with no problems. From the logs it looks like the DB connections were exhausted. Could you try again and let me know? Thank you! Sorry for the inconvenience

**Comment by jcubic** [comment]
Same, error. Also tried with dev tools open where cache is disabled.

**Comment by eddiejaoude** [comment]
Ah ok, I found the bug, deploying the fix now. I will reply when complete in about 10 minutes. Thank you again for taking the time to report the bug

**Comment by eddiejaoude** [comment]
The new version is deployed, it should be fixed now, sorry for the hassles @jcubic

**Comment by bruno-keiko** [comment]
@eddiejaoude It gives this error "Try signing in with a different account."

**Comment by eddiejaoude** [comment]
Thank you @bruno-keiko for testing, just to clarify: you are a new user and you are doing this on the deployed version (production, not locally)?

**Comment by eddiejaoude** [comment]
I can't replicate on production https://healthcheck.eddiehubcommunity.org

- new account: I just created a new test GitHub account and was able to log in successfully
- existing account: able to log in successfully using my usual GitHub account

**Comment by bruno-keiko** [comment]
> Thank you @bruno-keiko for testing, just to clarify:
> 
> * you are a new user
> * you are doing this on the deployed version (production, not locally)
> * and at the bottom left it says `v0.34.6`
> 
> Please confirm those 3 points?

I have cloned this repository and I want to run it locally for a pull request.

**Comment by eddiejaoude** [comment]
@bruno-keiko please come and chat in EddieHub Discord, because this issue is about production not local development setup

**Comment by jcubic** [comment]
I can confirm, the login works fine now.

**Comment by eddiejaoude** [comment]
ok phew, thanks @jcubic for confirming 👍  I will close the issue

Sorry for the hassles and confusion. I now need to write an automated test for new users, 2nd time the tests run they are an existing user 🤦‍♂️
