### ISSUE TITLE
[FEATURE] Favicon

### ISSUE THREAD

**Issue by jcubic** [EddieHubCommunity/HealthCheck#245]
### Description

It would be nice to have favicon so you can recognize the project in open tabs.
I usually use the project logo and [realfavicongenerator.net](https://realfavicongenerator.net/).

**Comment by eddiejaoude** [comment]
Great idea 👍  We have a logo that I think would work well as a favicon.

I wasn't aware of https://realfavicongenerator.net, so thank you 🔥

**Comment by eddiejaoude** [comment]
## LOGO

![logo](https://github.com/user-attachments/assets/6af5f110-f19a-4c61-b14c-9b3d284c7ff0)

## Favicon

[favicon_package_v0.zip](https://github.com/user-attachments/files/16978378/favicon_package_v0.zip)

**Comment by eddiejaoude** [comment]
Fixed in this commit 🎉 https://github.com/EddieHubCommunity/HealthCheck/commit/dce96fb1c954624a034c73f301d6a3dbfde591ce

<img width="195" alt="Screenshot 2024-09-12 at 13 13 12" src="https://github.com/user-attachments/assets/5d87fdc3-4e5b-4d14-9172-f68704cc9477">
