### ISSUE TITLE
[FEATURE] PR auto merger

### ISSUE THREAD

**Issue by Bashamega** [EddieHubCommunity/HealthCheck#250]
### Description

Hello:)
My idea is to adda workflow that will automatically merge a pr from [dependabot bot](https://github.com/apps/dependabot) if all checks are success

**Comment by eddiejaoude** [comment]
Thank you for the suggestion, but I prefer to test the project first with the new versions. Because it is more difficult to fix later and it can bring down production - which will make the project unstable.
