### ISSUE TITLE
[FEATURE] Adding Docker to the project

### ISSUE THREAD

**Issue by the-mzakrzewski** [EddieHubCommunity/HealthCheck#29]
### Description

Long story short: Dockerize Project :)

### Additional information

I can create proper Docker images and Docker compose config.

**Comment by eddiejaoude** [comment]
Thank you @the-mzakrzewski , I have assigned it to you

**Comment by eddiejaoude** [comment]
Merged https://github.com/EddieHubCommunity/HealthCheck/pull/30
