### ISSUE TITLE
[FEATURE] GitHub Action to create releases

### ISSUE THREAD

**Issue by SaraJaoude** [EddieHubCommunity/HealthCheck#3]
### Description

We use conventional commit messages that will trigger the release creation via the GitHub Action.

**Comment by eddiejaoude** [comment]
<img width="1265" alt="Screenshot 2024-07-09 at 18 28 21" src="https://github.com/EddieHubCommunity/HealthCheck/assets/624760/ee8bbbaa-59f0-4d12-a57b-c85446446783">
