### ISSUE TITLE
BUG: Description warning when repo URL is empty

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/HealthCheck#46]
### Description

In the "description" check, it checks if the repo url exists in the description, but when the "url" is empty it should not perform this check

This condition should also have the extra condition added `repo.homepage.length > 0`
https://github.com/EddieHubCommunity/HealthCheck/blob/8222a29b6be780801cbf979cf5e4608822d83c20/src/utils/checks/description.js#L36

Making the final line become

```diff
- if (repo.description.includes(repo.homepage)) {
+ if (repo.homepage.length > 0 && repo.description.includes(repo.homepage)) {
```

### Screenshots

<img width="1269" alt="Screenshot 2024-07-21 at 19 04 09" src="https://github.com/user-attachments/assets/0d2d508a-044e-42d4-897c-1ba7dbb2a60e">

### Additional information

You can visit this page on `http://localhost:3000/account/repo/report/{ID}`

**Comment by eddiejaoude** [comment]
@wotta please comment here, so we can assign it to you

**Comment by wotta** [comment]
Aah sure thing. Was working on this about an hour ago. But my docker is breaking, might pick it up tomorrow when docker is actually doing what I want again.

**Comment by eddiejaoude** [comment]
Sure no worries! Share the error, as it might be your local but could also be a bug

**Comment by wotta** [comment]
It has to do with an update of docker itself which I did. So for people watching, don't update docker on windows with wsl at the moment.
