### ISSUE TITLE
[FEATURE] Playwight mock authentication

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/HealthCheck#60]
### Description

Test authenticated (logged in pages) with Playwright

### Additional information

This was done with BioDrop https://github.com/EddieHubCommunity/BioDrop/blob/main/tests/setup/auth.js

Note: in BioDrop another ORM was used

**Comment by amandamartin-dev** [comment]
Livestream build!

**Comment by amandamartin-dev** [comment]
Article from @dan-mba to consider https://dev.to/votemike/server-side-mocking-for-playwright-in-nextjs-using-mock-service-worker-4p6g
