### ISSUE TITLE
[DOCS] Missing Security.md file

### ISSUE THREAD

**Issue by Bashamega** [EddieHubCommunity/HealthCheck#65]
### Description

Hello:)

The `Security.md` file is not there.

### Screenshots

![image](https://github.com/user-attachments/assets/615507f8-4ad6-4909-b9d3-f3fc82484218)

### Additional information

I would like to work on that

**Comment by eddiejaoude** [comment]
Thank you for raising 👍 

Sure, I can assign it to you. Please copy the content from the BioDrop repo

**Comment by Bashamega** [comment]
> Thank you for raising 👍
> 
> Sure, I can assign it to you. Please copy the content from the BioDrop repo

Your welcome
