### ISSUE TITLE
[FEATURE] Limit how many repos + checks can be added per user

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/HealthCheck#72]
### Description

The data could get very large, so we need to have a limit of how many repos can be added

1. display total and remaining (10 repos)
2. disable add button and server action if limit reached
3. limit how many checks can be done per repo, display total and remaining (10 checks)
4. disable the run button and server action if limit reached

Qs.
1. ~~should the repo have a delete button?~~ this can come later after it is deployed and we have user feedback
2. ~~should the checks have a delete button or expire after a certain amount of time?~~ same as point 1 above

**Comment by the-mzakrzewski** [comment]
I am willing to work on this if you are looking for someone @eddiejaoude :)

**Comment by eddiejaoude** [comment]
Sure Michal 👍 that would be great. I will assign it to you

**Comment by the-mzakrzewski** [comment]
@eddiejaoude if this is something important and you are waiting for those changes, please remove me from this task because I have a lot of stuff to do now

If this can wait I will do it later, sorry

**Comment by eddiejaoude** [comment]
no problem @the-mzakrzewski. Yep this is something we need before we can deploy, so I will assign it to myself, thanks for letting me know
