### ISSUE TITLE
[OTHER] Prettier Integration

### ISSUE THREAD

**Issue by Bashamega** [EddieHubCommunity/HealthCheck#77]
### What would you like to share?

Hello:)

I have noticed that this repo is missing prettier. I think formatted code can help people read the code.

### Additional information

I would like to work on this

**Comment by eddiejaoude** [comment]
Great! NextJS has a recommended way to setup Prettier in their docs https://nextjs.org/docs/pages/building-your-application/configuring/eslint#prettier
